### ISSUE TITLE
When I run main.py, it tells me that I don't have utils.AF, where should I find that file or the library

### ISSUE THREAD

**Issue by hajoxs** [xavysp/TEED#13]
Traceback (most recent call last):
  File "f:\subject\code\TEED-main\main.py", line 18, in <module>
    from loss2 import *
  File "f:\subject\code\TEED-main\loss2.py", line 3, in <module>
    from utils.AF.Fsmish import smish as Fsmish
ModuleNotFoundError: No module named 'utils.AF'

**Comment by xavysp** [comment]
Hi, thanks for interesting in TEED, you can see this function in: https://github.com/xavysp/TEED/tree/main/utils/AF

**Comment by hajoxs** [comment]
thanks
